# Generated by Django 4.0 on 2021-12-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('posted_by', models.CharField(default='Admin', max_length=20)),
                ('body', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
