# Generated by Django 4.0 on 2021-12-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
